### ISSUE TITLE
Use API token to access API

### ISSUE THREAD

**Issue by elgohr** [blackducksoftware/hub-client-go#30]
I'm just wondering how to use the API token (https://synopsys.atlassian.net/wiki/spaces/INTDOCS/pages/109477972/How+to+Generate+an+API+Token+in+Black+Duck) for accessing the API.
I'm not finding it in any implementation or documentation - just in the scanner.

**Comment by tandr** [comment]
`hubclient.NewWithApiToken` and `hubclient.NewWithApiTokenAndClient` are accepting API tokens.

`hubclient` also have `client.CreateApiToken`, `client.DeleteApiToken` and `client.ListApiTokens` to create, delete and enumerate them. 

HTH

**Comment by elgohr** [comment]
This issue is about the API, not the CLI or SDK.

**Comment by elgohr** [comment]
Thank you @Th3Lourde 

> Authentication
Black Duck enables you to generate one or more tokens for accessing Black Duck APIs. With access tokens, if a security breach occurs, the user’s credentials (which might be their SSO or LDAP credentials) are not directly compromised.
To access Black Duck API, you must authenticate by doing the following steps::
> 1. Generate an API token in Black Duck by going to the Black Duck UI, and from the user menu located on the top navigation bar, select My Access Tokens to open the My Access Tokens page where you generate your API token.
> 2. Pass the API token in an HTTP POST to /api/tokens/authenticate to generate a Bearer token, which you use for authorization.
> 3. Pass the bearer token in the authorization header of you API requests to get data from your Black Duck instance.

This was exactly the documentation that I was looking for
