### ISSUE TITLE
Latest updates to package reference internal synopsys repo

### ISSUE THREAD

**Issue by johnmccabe** [blackducksoftware/hub-client-go#44]
Hi @cpedlar-syn your recent addition of `hubclient/vulnerability-client.go` includes a reference to a private Synopsys package which outside users will not have access to, can this be replaced with a publically accessible dependency please.

    "sig-gitlab.internal.synopsys.com/sig-desktop/desktop-controller/controller/log"

**Comment by cpedlar-syn** [comment]
My bad, I didn't notice my auto imports selected that one.  I've changed to use logrus like the rest of the library in https://github.com/blackducksoftware/hub-client-go/pull/43 which also reverts some other issues that change caused.

**Comment by tandr** [comment]
I closing it as resolved.
