### ISSUE TITLE
PolicyViolationDetails in ProjectVersionPolicyStatus is a struct not an array

### ISSUE THREAD

**Issue by vasu-git** [blackducksoftware/hub-client-go#46]
In project-api.go module,
in the struct ProjectVersionPolicyStatus , PolicyViolationDetails is defined as an array of PolicyViolationDetail. However based on the response received from blackduck server , it looks like it is not an array but just a struct.
It should be 
**PolicyViolationDetails PolicyViolationDetail `json:"componentVersionPolicyViolationDetails"`**
rather than
**PolicyViolationDetails []PolicyViolationDetail `json:"componentVersionPolicyViolationDetails"`**

**Comment by tandr** [comment]
Thank you for reporting this. You are absolutely right - it is a struct!. It will be fixed in an upcoming commit.
