### ISSUE TITLE
Consider merging hubclient and hubapi package to only need one import

### ISSUE THREAD

**Issue by brekelj1** [blackducksoftware/hub-client-go#52]
Is there any reason the hubapi and hubclient packages are separate?
If users want need to declare response types then they have to additionally import the hubapi package. It would be easier for users in this case to only have to import one package.

**Comment by tandr** [comment]
Some places need only hubapi packages with definitions only, and don't want to pull http client part with all of associated dependencies

**Comment by brekelj1** [comment]
Hi @tandr 
I don't think placing packages in different directories of the same repository achieves what you want.
I believe the go tools checkout the repository at a given commit, and then use that checkout to resolve directories within the package's repository. I.e. `import "bla.com/pkg.git/bla"` will result in the repository `bla.com/pkg.git` being cloned, and then it looks for the `bla` directory in the checkout.

**Comment by tandr** [comment]
So... I have a package that uses only hubapi because I need definitions of the structures only (to parse json). I don't need the http client stuff. Right now it will be just one directory in my vendor directory. Putting them together will make me to pull dependencies that I don't need at all just to compile my project.

**Comment by brekelj1** [comment]
You are right that go tools won't copy the files in the vendor directory, but:
1. Go tools will still download those files.
1. The go compiler won't compile code that is not imported.
It is common for google client packages to follow this approach, for example:
1. https://github.com/google/go-github/tree/master/github
1. https://godoc.org/google.golang.org/api/compute/v1
