### ISSUE TITLE
Undeclared variables on hubclient tests

### ISSUE THREAD

**Issue by fnxpt** [blackducksoftware/hub-client-go#79]
I found 2 undeclared variables on test

apiCurrentUser:
https://github.com/blackducksoftware/hub-client-go/blob/00c30a1cdbd1ae0a304ef28df6dfbbe08196719f/hubclient/client_test.go#L94
https://github.com/blackducksoftware/hub-client-go/blob/00c30a1cdbd1ae0a304ef28df6dfbbe08196719f/hubclient/client_test.go#L107

apiVulnerabilities:
https://github.com/blackducksoftware/hub-client-go/blob/00c30a1cdbd1ae0a304ef28df6dfbbe08196719f/hubclient/vulnerability-client_test.go#L28

**Comment by tandr** [comment]
@tarunsethi @cpedlar-syn 

Fellas, do these test pass on your environment? if they do, maybe there are some files or changes that need to be tricked in here?

**Comment by fnxpt** [comment]
well if you try to find those variables on those files you cannot find them, it seems that there is some missing code in there
