### ISSUE TITLE
Add jobs

### ISSUE THREAD

**Issue by mattfenwick** [blackducksoftware/hub-client-go#9]
Example URL:

```
https://<base_hub_url>/api/v1/jobs?limit=100&sortField=scheduledAt&ascending=false&offset=1200
```

But!  Should the `v1` portion be handled differently due to the Hub changing how it handles versioning?

**Comment by mattfenwick** [comment]
@robpacheco is this a public API that we can use, or does the `v1` in the URL mean that we should be handling the version differently?

**Comment by robpacheco** [comment]
There currently is not a public API for jobs. Typically we don't use v1 APIs outside of internal Hub processing since there is no guarantee of stability with V1 APIs. Hub would need to add a public API before jobs APIs can be used outside of internal hub processing.
